# Native audio adapters. Downloads are pinned and verified before use.
set(AUDIO_DEPS "$ENV{ECHOPANE_AUDIO_DEPS}")
if(NOT AUDIO_DEPS)
  set(AUDIO_DEPS "${CMAKE_BINARY_DIR}/audio-deps")
endif()
file(TO_CMAKE_PATH "${AUDIO_DEPS}" AUDIO_DEPS)
file(MAKE_DIRECTORY "${AUDIO_DEPS}")
function(audio_download name url hash)
  set(destination "${AUDIO_DEPS}/${name}")
  if(EXISTS "${destination}")
    file(SHA256 "${destination}" actual_hash)
  endif()
  if(NOT actual_hash STREQUAL hash)
    file(DOWNLOAD "${url}" "${destination}" EXPECTED_HASH "SHA256=${hash}"
      TLS_VERIFY ON STATUS download_status)
    list(GET download_status 0 code)
    if(NOT code EQUAL 0)
      message(FATAL_ERROR "Could not download ${name}: ${download_status}")
    endif()
  endif()
endfunction()
audio_download(whisper.zip "https://codeload.github.com/ggml-org/whisper.cpp/zip/refs/tags/v1.9.4"
  873e67727d51213d3a14a6700c7415900a6645b78c4e6edad9328eea90e53572)
audio_download(miniaudio-fixed.h "https://raw.githubusercontent.com/mackron/miniaudio/1df46ae9a0eed5aa9f58b179d2cc4af5d23f8bde/miniaudio.h"
  d527621d96c281e37bfaffc482210b6dabad663bf35126a760b5c2e648e9282a)
if(NOT EXISTS "${AUDIO_DEPS}/whisper.cpp-1.9.4/include/whisper.h")
  execute_process(COMMAND "${CMAKE_COMMAND}" -E tar xf "${AUDIO_DEPS}/whisper.zip"
    WORKING_DIRECTORY "${AUDIO_DEPS}" RESULT_VARIABLE extracted)
  if(NOT extracted EQUAL 0)
    message(FATAL_ERROR "Could not extract whisper.cpp")
  endif()
endif()
enable_language(C)
set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(WHISPER_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_SERVER OFF CACHE BOOL "" FORCE)
set(WHISPER_BUILD_IS_DEV OFF CACHE BOOL "" FORCE)
set(GGML_NATIVE OFF CACHE BOOL "" FORCE)
set(GGML_OPENMP OFF CACHE BOOL "" FORCE)
set(GGML_BACKEND_DL ON CACHE BOOL "" FORCE)
set(GGML_CPU_ALL_VARIANTS ON CACHE BOOL "" FORCE)
set(GGML_AVX OFF CACHE BOOL "" FORCE)
set(GGML_AVX2 OFF CACHE BOOL "" FORCE)
set(GGML_FMA OFF CACHE BOOL "" FORCE)
set(GGML_F16C OFF CACHE BOOL "" FORCE)
set(GGML_BMI2 OFF CACHE BOOL "" FORCE)
function(audio_add_whisper)
  # Keep native inference optimized in Debug as well; retain the Debug CRT and symbols.
  # Flutter's runner remains debuggable with its normal compiler settings.
  set(CMAKE_C_FLAGS_DEBUG "/MDd /Zi /O2 /Ob2")
  set(CMAKE_CXX_FLAGS_DEBUG "/MDd /Zi /O2 /Ob2")
  add_subdirectory("${AUDIO_DEPS}/whisper.cpp-1.9.4" "${CMAKE_BINARY_DIR}/whisper" EXCLUDE_FROM_ALL)
endfunction()
audio_add_whisper()
set(AUDIO_RUNTIME_LIBRARIES "$<TARGET_FILE:whisper>" "$<TARGET_FILE:ggml>" "$<TARGET_FILE:ggml-base>")
foreach(variant x64 sse42 sandybridge haswell skylakex cannonlake cascadelake icelake alderlake)
  list(APPEND AUDIO_RUNTIME_LIBRARIES "$<TARGET_FILE:ggml-cpu-${variant}>")
endforeach()
set(AUDIO_RUNTIME_LIBRARIES "${AUDIO_RUNTIME_LIBRARIES}" PARENT_SCOPE)
add_library(echopane_audio STATIC audio_engine.cpp)
target_compile_features(echopane_audio PRIVATE cxx_std_20)
target_compile_options(echopane_audio PRIVATE /utf-8 /wd4996)
target_compile_definitions(echopane_audio PRIVATE NOMINMAX _CRT_SECURE_NO_WARNINGS)
target_include_directories(echopane_audio PRIVATE "${AUDIO_DEPS}")
target_link_libraries(echopane_audio PUBLIC whisper ole32)
